---
_extends: .github

repository:
  name: echobot-jvm
  description: Java echo bot example
  topics: java, toxcore, echobot
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - continuous-integration/appveyor/pr
          - security/snyk (TokTok)
